export const navItems = [
  ["dashboard", "Dashboard", "/"],
  ["users", "Users", "/users"],
  ["games", "Games", "/games"],
  ["star", "Reviews", "/reviews"],
  ["comment", "Comments", "/comments"],
  ["list", "Lists", "/lists"],
  ["flag", "Reports", "/reports"],
  ["bell", "Notifications", "/notifications"],
];

export const stats = [
  {
    icon: "users",
    label: "Total Users",
    value: "48,392",
    trend: "+12.4%",
    tone: "from-[#8e51ff] to-[#e12afb]",
  },
  {
    icon: "games",
    label: "Total Games",
    value: "2,847",
    trend: "+3.1%",
    tone: "from-[#00b8db] to-[#2b7fff]",
  },
  {
    icon: "star",
    label: "Total Reviews",
    value: "184,021",
    trend: "+18.7%",
    tone: "from-[#ff8a00] to-[#ff5f1f]",
  },
  {
    icon: "pulse",
    label: "Active Users",
    value: "12,540",
    trend: "-2.3%",
    tone: "from-[#21d4a6] to-[#00b894]",
    negative: true,
  },
];

export const reviews = [
  ["avatar-1.png", "ShadowStrike", "Elden Ring II", "2m ago", 5],
  ["avatar-2.png", "PixelQueen", "Hollow Knight: Silksong", "8m ago", 5],
  ["avatar-3.png", "NovaByte", "Cyberpunk 2078", "14m ago", 3],
  ["avatar-4.png", "RetroKnight", "Stardew Valley 2", "22m ago", 4],
  ["avatar-5.png", "VoidWalker", "Hades II", "31m ago", 5],
];

export const reviewRows = [
  {
    avatar: "avatar-1.png",
    user: "ShadowStrike",
    game: "Elden Ring II",
    rating: 5,
    status: "Latest",
    time: "2h ago",
    likes: "1,240",
    comments: "84",
    text: "An absolute masterpiece. The world design is breathtaking and the combat system feels refined to perfection.",
  },
  {
    avatar: "avatar-2.png",
    user: "PixelQueen",
    game: "Hollow Knight: Silksong",
    rating: 5,
    status: "Latest",
    time: "5h ago",
    likes: "892",
    comments: "51",
    text: "Worth every minute of the wait. Hornet's moveset is exhilarating and the new biomes are gorgeous.",
  },
  {
    avatar: null,
    user: "ToxicGamer42",
    game: "Cyberpunk 2078",
    rating: 3,
    status: "Reported",
    time: "1d ago",
    likes: "4",
    comments: "12",
    text: "[Content flagged for review -- slurs detected]",
  },
  {
    avatar: null,
    user: "NovaByte",
    game: "Hades II",
    rating: 4,
    status: "Latest",
    time: "3h ago",
    likes: "412",
    comments: "27",
    text: "Melinoe is a great protagonist but I miss Zagreus's voice lines. Still, gameplay is top tier.",
  },
  {
    avatar: "avatar-4.png",
    user: "RetroKnight",
    game: "Stardew Valley 2",
    rating: 5,
    status: "Latest",
    time: "8h ago",
    likes: "678",
    comments: "39",
    text: "Cozy gaming at its finest. ConcernedApe has done it again.",
  },
];

export const commentRows = [
  {
    avatar: "avatar-1.png",
    user: "GamerX99",
    context: "on Elden Ring II review by ShadowStrike",
    status: "Published",
    time: "12m ago",
    text: "Couldn't agree more, this game changed my life.",
  },
  {
    avatar: "avatar-2.png",
    user: "Spammer123",
    context: "on Hades II review by NovaByte",
    status: "Flagged",
    time: "1h ago",
    text: "CHECK OUT MY CHANNEL!!! free skins click link!!!",
  },
  {
    avatar: "avatar-3.png",
    user: "PixelQueen",
    context: "on Stardew Valley 2 review by RetroKnight",
    status: "Published",
    time: "2h ago",
    text: "Cozy is exactly the right word.",
  },
  {
    avatar: "avatar-4.png",
    user: "ToxicGamer42",
    context: "on Cyberpunk 2078 review by NovaByte",
    status: "Flagged",
    time: "3h ago",
    text: "[Content flagged - harassment]",
  },
  {
    avatar: "avatar-5.png",
    user: "VoidWalker",
    context: "on Silksong review by PixelQueen",
    status: "Published",
    time: "5h ago",
    text: "Hornet supremacy. The bosses though...",
  },
  {
    avatar: "avatar-4.png",
    user: "LunaQuest",
    context: "on Outer Wilds: Echoes review",
    status: "Published",
    time: "8h ago",
    text: "Don't spoil it for new players please!",
  },
];

export const reportRows = [
  {
    icon: "users",
    tone: "bg-[#ff2c7d]",
    category: "User",
    title: "ToxicGamer42",
    detail: "Repeated harassment in comments",
    meta: "Reported by 14 users",
    time: "2h ago",
  },
  {
    icon: "star",
    tone: "bg-[#ff8a00]",
    category: "Review",
    title: "Review on Cyberpunk 2078",
    detail: "Slurs and offensive language",
    meta: "Reported by 23 users",
    time: "5h ago",
  },
  {
    icon: "comment",
    tone: "bg-[#2bafff]",
    category: "Comment",
    title: "Comment by Spammer123",
    detail: "Spam / promotional links",
    meta: "Reported by 8 users",
    time: "8h ago",
  },
  {
    icon: "users",
    tone: "bg-[#ff2c7d]",
    category: "User",
    title: "LinkBot99",
    detail: "Suspicious activity, possibly bot",
    meta: "Reported by 5 users",
    time: "1d ago",
  },
  {
    icon: "star",
    tone: "bg-[#ff8a00]",
    category: "Review",
    title: "Review on Hades II",
    detail: "Spoilers without warning",
    meta: "Reported by 11 users",
    time: "1d ago",
  },
];

export const notificationLogs = [
  {
    title: "Scheduled maintenance -- April 30",
    audience: "All users",
    reached: "48,392",
    time: "2h ago",
  },
  {
    title: "New release: Hollow Knight: Silksong page is live",
    audience: "Active users",
    reached: "12,540",
    time: "1d ago",
  },
  {
    title: "Community guidelines updated",
    audience: "All users",
    reached: "47,891",
    time: "3d ago",
  },
  {
    title: "Welcome reward for new accounts",
    audience: "New users",
    reached: "1,204",
    time: "1w ago",
  },
];

export const actions = [
  ["plusUser", "New user signed up: kira_plays", "Just now", "text-[#00d492]"],
  ["trash", "Review deleted (spam)", "5m ago", "text-[#ff2056]"],
  ["shield", "User suspended: toxic_gamer42", "12m ago", "text-[#ffb000]"],
  ["plusUser", "New user signed up: lunaquest", "18m ago", "text-[#00d492]"],
  ["trash", "Comment removed (harassment)", "26m ago", "text-[#ff2056]"],
];

export const userStats = [
  {
    icon: "users",
    label: "Total Users",
    value: "48,392",
    trend: "+12.4%",
    tone: "from-[#8e51ff] to-[#e12afb]",
  },
  {
    icon: "pulse",
    label: "Active Users",
    value: "12,540",
    trend: "+8.2%",
    tone: "from-[#00b8db] to-[#2b7fff]",
  },
  {
    icon: "plusUser",
    label: "New This Week",
    value: "1,248",
    trend: "+24.7%",
    tone: "from-[#21d4a6] to-[#00b894]",
  },
  {
    icon: "shield",
    label: "Suspended",
    value: "342",
    trend: "-2.1%",
    tone: "from-[#ff8a00] to-[#ff5f1f]",
    negative: true,
  },
];

export const users = [
  ["avatar-1.png", "ShadowStrike", "shadow@playlog.gg", "Active", "2,184", "Jan 12, 2026"],
  ["avatar-2.png", "PixelQueen", "pixel@playlog.gg", "Active", "1,943", "Jan 18, 2026"],
  ["avatar-3.png", "NovaByte", "nova@playlog.gg", "Pending", "843", "Feb 04, 2026"],
  ["avatar-4.png", "RetroKnight", "retro@playlog.gg", "Active", "712", "Feb 21, 2026"],
  ["avatar-5.png", "VoidWalker", "void@playlog.gg", "Suspended", "396", "Mar 02, 2026"],
];

export const games = [
  {
    title: "Elden Ring II",
    genre: "Action RPG",
    studio: "FromSoftware",
    status: "Published",
    platform: "PC, PS5, Xbox",
    rating: "4.8",
    reviews: "12,420 reviews",
    players: "842K",
    updated: "May 12, 2026",
    cover: "from-[#1d1616] via-[#111827] to-[#050608]",
    glow: "bg-[radial-gradient(circle_at_24%_20%,rgba(255,255,255,0.35),transparent_18%),radial-gradient(circle_at_78%_30%,rgba(67,56,202,0.32),transparent_24%),linear-gradient(135deg,rgba(0,0,0,0.15),rgba(0,0,0,0.75))]",
  },
  {
    title: "Cyberpunk 2078",
    genre: "Open World",
    studio: "CD Projekt Red",
    status: "Review",
    platform: "PC, PS5",
    rating: "4.2",
    reviews: "8,932 reviews",
    players: "512K",
    updated: "May 10, 2026",
    cover: "from-[#0694cf] via-[#1d0f46] to-[#020308]",
    glow: "bg-[radial-gradient(circle_at_56%_16%,rgba(0,229,255,0.85),transparent_18%),radial-gradient(circle_at_62%_65%,rgba(236,72,153,0.55),transparent_28%),linear-gradient(180deg,rgba(0,0,0,0.05),rgba(0,0,0,0.88))]",
  },
  {
    title: "Hollow Knight: Silksong",
    genre: "Metroidvania",
    studio: "Team Cherry",
    status: "Published",
    platform: "Switch, PC",
    rating: "4.9",
    reviews: "15,203 reviews",
    players: "1.2M",
    updated: "May 09, 2026",
    cover: "from-[#d8e8f2] via-[#71a5c8] to-[#080a0f]",
    glow: "bg-[radial-gradient(circle_at_52%_28%,rgba(255,255,255,0.85),transparent_22%),radial-gradient(circle_at_72%_58%,rgba(64,64,64,0.55),transparent_20%),linear-gradient(180deg,rgba(255,255,255,0.08),rgba(0,0,0,0.9))]",
  },
  {
    title: "Hades II",
    genre: "Roguelike",
    studio: "Supergiant",
    status: "Draft",
    platform: "PC",
    rating: "4.7",
    reviews: "9,874 reviews",
    players: "693K",
    updated: "May 08, 2026",
    cover: "from-[#0094c8] via-[#082840] to-[#020508]",
    glow: "bg-[radial-gradient(circle_at_64%_24%,rgba(0,212,255,0.58),transparent_25%),radial-gradient(circle_at_50%_58%,rgba(14,165,233,0.45),transparent_24%),linear-gradient(180deg,rgba(0,0,0,0.05),rgba(0,0,0,0.9))]",
  },
  {
    title: "Stardew Valley 2",
    genre: "Simulation",
    studio: "ConcernedApe",
    status: "Published",
    platform: "PC, Switch",
    rating: "4.9",
    reviews: "7,621 reviews",
    players: "477K",
    updated: "May 06, 2026",
    cover: "from-[#d9e6dd] via-[#8a7c43] to-[#10150d]",
    glow: "bg-[radial-gradient(circle_at_34%_20%,rgba(255,255,255,0.72),transparent_24%),radial-gradient(circle_at_48%_58%,rgba(245,158,11,0.45),transparent_28%),linear-gradient(180deg,rgba(255,255,255,0.05),rgba(0,0,0,0.9))]",
  },
  {
    title: "Outer Wilds: Echoes",
    genre: "Adventure",
    studio: "Mobius Digital",
    status: "Archived",
    platform: "PC, Xbox",
    rating: "4.6",
    reviews: "4,321 reviews",
    players: "209K",
    updated: "May 03, 2026",
    cover: "from-[#0ea5e9] via-[#151539] to-[#020308]",
    glow: "bg-[radial-gradient(circle_at_58%_27%,rgba(14,165,233,0.65),transparent_18%),radial-gradient(circle_at_65%_60%,rgba(236,72,153,0.45),transparent_24%),linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.9))]",
  },
];
